### ISSUE TITLE
TypeError: new(): data must be a sequence (got map)

### ISSUE THREAD

**Issue by Huleryo** [keishinkickback/Pytorch-RNN-text-classification#1]
Which Python version should I use?

When I used Python3 run the main.py I got an error:
Traceback (most recent call last):
  File "main.py", line 179, in <module>
    train(train_loader, model, criterion, optimizer, epoch)
  File "main.py", line 102, in train
    for i, (input, target, seq_lengths) in enumerate(train_loader):
  File "/media/yu/Work/ml/dl/case/Pytorch-RNN-text-classification-master/dataloader.py", line 108, in __iter__
    yield self._create_batch()
  File "/media/yu/Work/ml/dl/case/Pytorch-RNN-text-classification-master/dataloader.py", line 82, in _create_batch
    seq_lengths = torch.LongTensor(map(len, string))
TypeError: new(): data must be a sequence (got map)

**Comment by keishinkickback** [comment]
Hi Huleryo,

I run this code with Python2. Hope this is helpful.

**Comment by YazhuoGuan** [comment]
Hello Huleryo, 
I met a same problem. How did you solve it finally?

**Comment by keishinkickback** [comment]
Hi @YazhuoGuan,

You can use [pyenv](https://github.com/pyenv/pyenv) to which Python versions. This repo should work fine with Python2.7.
